### ISSUE TITLE
论文讨论

### ISSUE THREAD

**Issue by jackyyang-cv** [ly19965/MogFace#7]
问题：
       1. 论文与工程实现不一致。

**Comment by ly19965** [comment]
mark

**Comment by ly19965** [comment]
哪个部分复现不一致，请指出

**Comment by ly19965** [comment]
我的手机号是17801139006，你可以加我微信好友，我们语音讨论下。

**Comment by ly19965** [comment]
对了，如果你说的是最终的结果无法复现，还需要加deep head, pyramid anchor, multi-scale ensemble的trick，这是刷榜的技巧，可以看下ASFD paper也提过。另外，我刚对了下这几个模型的结果，全都与论文一致。
![image](https://user-images.githubusercontent.com/35597221/227681563-cca3bb23-17f0-47ec-8e94-76b41bdca6b2.png)

![image](https://user-images.githubusercontent.com/35597221/227681540-472e9143-13f5-4dd0-9015-7001c1627b3f.png)

**Comment by ly19965** [comment]
我有点越想越气，我所有的code，baseline都是从0到1自己写的，所有顶会人脸的paper精度我都在我的框架上加过，故事-level的paper是好听，你去试下本质涨点的原因是什么，不要听其他人的paper说啥是啥，但是我的可以。可不可以有更多的思考量，要看背后work的原因是什么，我paper中所列的实验在我的视角都非常有启发，你可能不会明白下面这个实验2,3行所代表的意义。这代表着，MST不是万能的，他只是适合coco的数据集分布，widerface小脸较多的情况，MST并不是一个reasonable的数据增强的方式，也就是说MST带来的scale信息网络无法有效学习到，这背后的原因是WiderFace前景太多了，如果不做RSC or DAS对image进行crop，网络是无法有效收敛的，基于这个发现，我们进一步控制了不同pyramid layer的前景分布，得到了下面表格的intesting 现象，你可以理解了吗？不是某个pyramid layer匹配到更多的gt，该层的检测能力越强。我真的建议做cv不要yy下结论，cv不是故事科学，看更多的故事会让你陷入错误的研究方向，我的理解是cv是实验科学，你要确保你说的每一句话都有实验作为支撑，这样你在做算法创新时哪怕简单但是你会有底气，知道自己做的东西背后有定量实验分析作为保障。
![image](https://user-images.githubusercontent.com/35597221/227688977-7923ef94-97d1-4864-86b3-7b2046e30451.png)
![image](https://user-images.githubusercontent.com/35597221/227689174-b391dc24-f4ff-4dfe-ae4c-e5ea1092852c.png)

**Comment by ly19965** [comment]
mark

**Comment by jackyyang-cv** [comment]
首先谢谢你的回复。
有两点问题：
1. 代码复现结果很差。建议提供可完全复现的工程，否则很难验证。
2. 代码实现与论文中(Algorithm 1 Adaptive Online Incremental Anchor Mining Strategy (Ali-AMS))所属的流程不一致，文章流程中添加了一些工程没有的东西，请确认。

**Comment by ly19965** [comment]
1. 代码复现很差，我理解我们paper分为两个部分，第一个部分是Ali-AMS, SSE和HCAM，这三个部分精度复现差的话应该不太可能，因为有其他人找过我，提过结果没问题，最多有0.2个点的seed波动，而且一般是结果上浮。第二个就是我们榜单冠军的模型，这个首先是不开源的，只release对应的模型进行测试，原因刷榜单冠军的时候用了很多的trick，method 角度像paper中介绍的我们额外用了Pyramid Anchor和deep head，只有这两个有涨点，但是也占了很多的显存，也不是很solid。trick-level我们用了multi-scale ensemble trick，预训练了一个pretrain的model，pretrain model中也有一些trick，以及更多的epoch，还有些调参的trick，这些都是刷榜的技巧，无需开源。最终Easy，Medium我们用了一个模型的结果，Hard我们用了6个模型的ensemble结果，其实release的出来是其中一个模型。看下跟我们论文同期的COCO冠军榜单（face++），也都说了自己用了emsemble的trick，代码也都没有开源，需要自己试错，几乎所有有点含金量的冠军都会这样做，我已经把人脸领域中work的方法列出来了，剩余都是调trick+调参了。如果你想刷榜单，需要自己一点点摸索哪些是有用的，或者用mmdetection架构（TinaFace），那个mmdetection有太多人维护了，很多东西都可以一键调用，无需自己coding，我这套确实有点过时了，要加东西需要自己coding。另外，我们的冠军模型的结果是提交到官网得到的验证曲线。
2. 首先，Ali-AMS只修改了这个https://github.com/damo-cv/MogFace/blob/master/configs/mogface/MogFace_Ali-AMS.yml#L49-L53。这个修改的部分这里是我们的核心代码，https://github.com/damo-cv/MogFace/blob/master/modelling/criterion.py#L139-L171。我刚读了下，跟paper中描述的只差在candidate idx没有加IoU的candidate_idx，如果是这个，我找一下相关的配置文件，重新跑下结果，然后release出来，但是整体的流程跟论文中是完全一致的。

**Comment by jackyyang-cv** [comment]
问题1：用你提供的模型测试是没有问题的，但是如果从头训练出来的结果差异很多。你所列的tirck可以不用开源，但是开源工程需要和readme中的结果对齐吧。或者说你做的工作使得提升了多少。
问题2：工程我很久之前研究过，仔细阅读你的代码和文章比对，发现代码流程和文章流程不能对齐。
如果你的工作确实是有效和work的并且开源的代码可以对比出结果，请告知我，我会尝试花时间阅读代码。

**Comment by ly19965** [comment]
问题1： 我才明白，你说的这个结果对不齐？你发下你的结果，现在是你说对不齐。我觉得你可以稍微讲下道理，考虑下是否自己哪里有问题。下面是以前的朋友复现的结果，Hard上高了0.1个点。。Easy，Medium数据量太少，有点波动可以理解吧，Hard上是WiderFace的全集。
![image](https://user-images.githubusercontent.com/35597221/227835104-dde60903-90d6-4445-95d2-651c34094605.png)


问题2：代码流程和文章流程不能对齐，我刚才解释的很清楚了，整个流程都是对齐的，差了个 idx没有加IoU的candidate_idx，现在这版本不影响精度，这个后续可以加上，其余都是对齐的。然后你现在对不齐，考虑下自己的环境吧，谢谢，你不能说我上面这张图片是p的吧。

**Comment by jackyyang-cv** [comment]
我说的是训练结果不对，这么快就训练完了吗？
你们训练的命令是什么，我复现一下，我这边有8卡A100，环境应该没有问题

**Comment by ly19965** [comment]
能看下这张图片吗，是去年朋友问我的相关问题，这个他的复现结果。训练代码是这个，  CUDA_VISIBLE_DEVICES=0,1,2,3 python train.py -c configs/mogface/MogFace_Ali-AMS.yml。由于下面这个图片能证明别人复现结果没问题，因此有结果差异是你环境的问题，按照我的README重新运行下。如果你跑了还有问题，把log和模型以及你的测试精度发我。“这么快就训练完了吗？”=>。。我哪句话说明了我训练完了？对了，如果你以前用8卡训练的话是可能结果对不齐的，8卡训练的话学习率和batch size也要对齐，才是一致的setting，所以如果你不修改配置文件的话建议这次训练用4卡训。如果要用8卡训的话建议看下这篇papaer“Accurate, Large Minibatch SGD: Training ImageNet in 1 Hour?“ 改下训练设置。

**Comment by jackyyang-cv** [comment]
下面是我之前实验的结果：
MogFace_Ali-AMS.yml 没有预训练 Easy: 0.92382386, Medium: 0.91627115, Hard: 0.85607411
MogFace_SSE.yml Test Iter: 70, Easy: 0.40417401, Medium: 0.51225465, Hard: 0.52956536
MogFace_base.yml 没有预训练 Easy: 0.93354306, Medium: 0.92644111, Hard: 0.8546858900000001

下面是retinaface的结果(https://github.com/deepinsight/insightface/tree/master/RetinaFace):
WiderFace validation mAP: Easy 96.5, Medium 95.6, Hard 90.4

从训练结果看不出你的工作有没有work，我之前是想看关掉AMS做对比，然后看到ams和论文有很多不一致。

**Comment by ly19965** [comment]
这个很明显了是你setting的问题了，自己再对齐下吧，我们和retinaface的setting完全不一致，不要一同比较，你把iter开到140000加个retinanet中的deep head 精度就起来了再加下1e-2学习率，精度会超过retinaface，另外和retinaface的测试代码你要保证是一致的，才能公平对比。另外没加预训练性能也不会差太多，我做过实验。”MogFace_SSE.yml Test Iter: 70, Easy: 0.40417401, Medium: 0.51225465, Hard: 0.52956536“这种实验结果都能跑出来就明显环境有问题。你看我放的微信图片，这是别人按照我的repo一步一步走复现的结果。AMS跟论文哪里不一致，我都给你引代码了。。
![image](https://user-images.githubusercontent.com/35597221/227863016-e814139b-9267-47a8-a784-7e80d4d0ee7b.png)

**Comment by ly19965** [comment]
你按照我的setting跑这个CUDA_VISIBLE_DEVICES=0,1,2,3 python train.py -c configs/mogface/MogFace_Ali-AMS.yml和base，我release了base的代码，或者你直接关掉AMS，是一样的，千万不要改我的代码，重新起个conda环境去运行，谢谢。
